#!/usr/bin/env ruby
#
# $Id: msfgui 10806 2010-10-24 00:57:50Z jduck $
#
# Graphical user interface written in Java with rpc.
#
# $Revision: 10806 $
#

msfbase = __FILE__
while File.symlink?(msfbase)
	msfbase = File.expand_path(File.readlink(msfbase), File.dirname(msfbase))
end

if RUBY_PLATFORM =~ /mswin|mingw/i
	exec "javaw -jar #{File.dirname(msfbase)}/data/gui/msfgui.jar"
else
	exec "java -jar #{File.dirname(msfbase)}/data/gui/msfgui.jar"
end
